USE master;
GO
--
SET NOCOUNT OFF;
--
-- Delete the Data from Child Tables and then Parent Tables in Reverse Order of Dependency
EXECUTE [w3schools].sys.sp_executesql @command = N'MERGE INTO [w3schools].[dbo].[OrderDetails] AS T USING [w3schools_copy].[dbo].[OrderDetails] AS S ON T.[OrderDetailID] = S.[OrderDetailID] WHEN NOT MATCHED BY SOURCE THEN DELETE ;';
EXECUTE [w3schools].sys.sp_executesql @command = N'MERGE INTO [w3schools].[dbo].[Orders] AS T USING [w3schools_copy].[dbo].[Orders] AS S ON T.[OrderID] = S.[OrderID] WHEN NOT MATCHED BY SOURCE THEN DELETE ;';
EXECUTE [w3schools].sys.sp_executesql @command = N'MERGE INTO [w3schools].[dbo].[Products] AS T USING [w3schools_copy].[dbo].[Products] AS S ON T.[ProductID] = S.[ProductID] WHEN NOT MATCHED BY SOURCE THEN DELETE ;';
EXECUTE [w3schools].sys.sp_executesql @command = N'MERGE INTO [w3schools].[dbo].[Categories] AS T USING [w3schools_copy].[dbo].[Categories] AS S ON T.[CategoryID] = S.[CategoryID] WHEN NOT MATCHED BY SOURCE THEN DELETE ;';
EXECUTE [w3schools].sys.sp_executesql @command = N'MERGE INTO [w3schools].[dbo].[Customers] AS T USING [w3schools_copy].[dbo].[Customers] AS S ON T.[CustomerID] = S.[CustomerID] WHEN NOT MATCHED BY SOURCE THEN DELETE ;';
EXECUTE [w3schools].sys.sp_executesql @command = N'MERGE INTO [w3schools].[dbo].[Employees] AS T USING [w3schools_copy].[dbo].[Employees] AS S ON T.[EmployeeID] = S.[EmployeeID] WHEN NOT MATCHED BY SOURCE THEN DELETE ;';
EXECUTE [w3schools].sys.sp_executesql @command = N'MERGE INTO [w3schools].[dbo].[Shippers] AS T USING [w3schools_copy].[dbo].[Shippers] AS S ON T.[ShipperID] = S.[ShipperID] WHEN NOT MATCHED BY SOURCE THEN DELETE ;';
EXECUTE [w3schools].sys.sp_executesql @command = N'MERGE INTO [w3schools].[dbo].[Suppliers] AS T USING [w3schools_copy].[dbo].[Suppliers] AS S ON T.[SupplierID] = S.[SupplierID] WHEN NOT MATCHED BY SOURCE THEN DELETE ;';
--
-- Insert the Data from Parent Tables and then Child Tables in Order of Dependency
EXECUTE [w3schools].sys.sp_executesql @command = N'SET IDENTITY_INSERT [w3schools].[dbo].[Categories] ON; MERGE INTO [w3schools].[dbo].[Categories] AS T USING [w3schools_copy].[dbo].[Categories] AS S ON T.[CategoryID] = S.[CategoryID] WHEN NOT MATCHED BY TARGET THEN INSERT ([CategoryID], [CategoryName], [Description]) VALUES (S.[CategoryID], S.[CategoryName], S.[Description]) ; SET IDENTITY_INSERT [w3schools].[dbo].[Categories] OFF; ';
EXECUTE [w3schools].sys.sp_executesql @command = N'SET IDENTITY_INSERT [w3schools].[dbo].[Customers] ON; MERGE INTO [w3schools].[dbo].[Customers] AS T USING [w3schools_copy].[dbo].[Customers] AS S ON T.[CustomerID] = S.[CustomerID] WHEN NOT MATCHED BY TARGET THEN INSERT ([CustomerID], [CustomerName], [ContactName], [Address], [City], [PostalCode], [Country]) VALUES (S.[CustomerID], S.[CustomerName], S.[ContactName], S.[Address], S.[City], S.[PostalCode], S.[Country]) ; SET IDENTITY_INSERT [w3schools].[dbo].[Customers] OFF; ';
EXECUTE [w3schools].sys.sp_executesql @command = N'SET IDENTITY_INSERT [w3schools].[dbo].[Employees] ON; MERGE INTO [w3schools].[dbo].[Employees] AS T USING [w3schools_copy].[dbo].[Employees] AS S ON T.[EmployeeID] = S.[EmployeeID] WHEN NOT MATCHED BY TARGET THEN INSERT ([EmployeeID], [LastName], [FirstName], [BirthDate], [Photo], [Notes]) VALUES (S.[EmployeeID], S.[LastName], S.[FirstName], S.[BirthDate], S.[Photo], S.[Notes]) ; SET IDENTITY_INSERT [w3schools].[dbo].[Employees] OFF; ';
EXECUTE [w3schools].sys.sp_executesql @command = N'SET IDENTITY_INSERT [w3schools].[dbo].[Shippers] ON; MERGE INTO [w3schools].[dbo].[Shippers] AS T USING [w3schools_copy].[dbo].[Shippers] AS S ON T.[ShipperID] = S.[ShipperID] WHEN NOT MATCHED BY TARGET THEN INSERT ([ShipperID], [ShipperName], [Phone]) VALUES (S.[ShipperID], S.[ShipperName], S.[Phone]) ; SET IDENTITY_INSERT [w3schools].[dbo].[Shippers] OFF; ';
EXECUTE [w3schools].sys.sp_executesql @command = N'SET IDENTITY_INSERT [w3schools].[dbo].[Suppliers] ON; MERGE INTO [w3schools].[dbo].[Suppliers] AS T USING [w3schools_copy].[dbo].[Suppliers] AS S ON T.[SupplierID] = S.[SupplierID] WHEN NOT MATCHED BY TARGET THEN INSERT ([SupplierID], [SupplierName], [ContactName], [Address], [City], [PostalCode], [Country]) VALUES (S.[SupplierID], S.[SupplierName], S.[ContactName], S.[Address], S.[City], S.[PostalCode], S.[Country]) ; SET IDENTITY_INSERT [w3schools].[dbo].[Suppliers] OFF; ';
EXECUTE [w3schools].sys.sp_executesql @command = N'SET IDENTITY_INSERT [w3schools].[dbo].[Orders] ON; MERGE INTO [w3schools].[dbo].[Orders] AS T USING [w3schools_copy].[dbo].[Orders] AS S ON T.[OrderID] = S.[OrderID] WHEN NOT MATCHED BY TARGET THEN INSERT ([OrderID], [CustID], [EmpID], [OrderDate], [ShipID]) VALUES (S.[OrderID], S.[CustID], S.[EmpID], S.[OrderDate], S.[ShipID]) ; SET IDENTITY_INSERT [w3schools].[dbo].[Orders] OFF; ';
EXECUTE [w3schools].sys.sp_executesql @command = N'SET IDENTITY_INSERT [w3schools].[dbo].[Products] ON; MERGE INTO [w3schools].[dbo].[Products] AS T USING [w3schools_copy].[dbo].[Products] AS S ON T.[ProductID] = S.[ProductID] WHEN NOT MATCHED BY TARGET THEN INSERT ([ProductID], [ProductName], [SuplID], [CatID], [Unit], [Price]) VALUES (S.[ProductID], S.[ProductName], S.[SuplID], S.[CatID], S.[Unit], S.[Price]) ; SET IDENTITY_INSERT [w3schools].[dbo].[Products] OFF; ';
EXECUTE [w3schools].sys.sp_executesql @command = N'SET IDENTITY_INSERT [w3schools].[dbo].[OrderDetails] ON; MERGE INTO [w3schools].[dbo].[OrderDetails] AS T USING [w3schools_copy].[dbo].[OrderDetails] AS S ON T.[OrderDetailID] = S.[OrderDetailID] WHEN NOT MATCHED BY TARGET THEN INSERT ([OrderDetailID], [OrdID], [ProdID], [Quantity]) VALUES (S.[OrderDetailID], S.[OrdID], S.[ProdID], S.[Quantity]) ; SET IDENTITY_INSERT [w3schools].[dbo].[OrderDetails] OFF; ';
--
-- Update the Data in Parent Tables and then Child Tables in Order of Dependency
EXECUTE [w3schools].sys.sp_executesql @command = N'MERGE INTO [w3schools].[dbo].[Categories] AS T USING [w3schools_copy].[dbo].[Categories] AS S ON T.[CategoryID] = S.[CategoryID] WHEN MATCHED AND ISNULL(T.[CategoryName], '''') != ISNULL(S.[CategoryName], '''') OR ISNULL(T.[Description], '''') != ISNULL(S.[Description], '''') THEN UPDATE SET T.[CategoryName] = S.[CategoryName], T.[Description] = S.[Description] ;';
EXECUTE [w3schools].sys.sp_executesql @command = N'MERGE INTO [w3schools].[dbo].[Customers] AS T USING [w3schools_copy].[dbo].[Customers] AS S ON T.[CustomerID] = S.[CustomerID] WHEN MATCHED AND ISNULL(T.[CustomerName], '''') != ISNULL(S.[CustomerName], '''') OR ISNULL(T.[ContactName], '''') != ISNULL(S.[ContactName], '''') OR ISNULL(T.[Address], '''') != ISNULL(S.[Address], '''') OR ISNULL(T.[City], '''') != ISNULL(S.[City], '''') OR ISNULL(T.[PostalCode], '''') != ISNULL(S.[PostalCode], '''') OR ISNULL(T.[Country], '''') != ISNULL(S.[Country], '''') THEN UPDATE SET T.[CustomerName] = S.[CustomerName], T.[ContactName] = S.[ContactName], T.[Address] = S.[Address], T.[City] = S.[City], T.[PostalCode] = S.[PostalCode], T.[Country] = S.[Country] ;';
EXECUTE [w3schools].sys.sp_executesql @command = N'MERGE INTO [w3schools].[dbo].[Employees] AS T USING [w3schools_copy].[dbo].[Employees] AS S ON T.[EmployeeID] = S.[EmployeeID] WHEN MATCHED AND ISNULL(T.[LastName], '''') != ISNULL(S.[LastName], '''') OR ISNULL(T.[FirstName], '''') != ISNULL(S.[FirstName], '''') OR ISNULL(T.[BirthDate], '''') != ISNULL(S.[BirthDate], '''') OR ISNULL(T.[Photo], '''') != ISNULL(S.[Photo], '''') OR ISNULL(T.[Notes], '''') != ISNULL(S.[Notes], '''') THEN UPDATE SET T.[LastName] = S.[LastName], T.[FirstName] = S.[FirstName], T.[BirthDate] = S.[BirthDate], T.[Photo] = S.[Photo], T.[Notes] = S.[Notes] ;';
EXECUTE [w3schools].sys.sp_executesql @command = N'MERGE INTO [w3schools].[dbo].[Shippers] AS T USING [w3schools_copy].[dbo].[Shippers] AS S ON T.[ShipperID] = S.[ShipperID] WHEN MATCHED AND ISNULL(T.[ShipperName], '''') != ISNULL(S.[ShipperName], '''') OR ISNULL(T.[Phone], '''') != ISNULL(S.[Phone], '''') THEN UPDATE SET T.[ShipperName] = S.[ShipperName], T.[Phone] = S.[Phone] ;';
EXECUTE [w3schools].sys.sp_executesql @command = N'MERGE INTO [w3schools].[dbo].[Suppliers] AS T USING [w3schools_copy].[dbo].[Suppliers] AS S ON T.[SupplierID] = S.[SupplierID] WHEN MATCHED AND ISNULL(T.[SupplierName], '''') != ISNULL(S.[SupplierName], '''') OR ISNULL(T.[ContactName], '''') != ISNULL(S.[ContactName], '''') OR ISNULL(T.[Address], '''') != ISNULL(S.[Address], '''') OR ISNULL(T.[City], '''') != ISNULL(S.[City], '''') OR ISNULL(T.[PostalCode], '''') != ISNULL(S.[PostalCode], '''') OR ISNULL(T.[Country], '''') != ISNULL(S.[Country], '''') THEN UPDATE SET T.[SupplierName] = S.[SupplierName], T.[ContactName] = S.[ContactName], T.[Address] = S.[Address], T.[City] = S.[City], T.[PostalCode] = S.[PostalCode], T.[Country] = S.[Country] ;';
EXECUTE [w3schools].sys.sp_executesql @command = N'MERGE INTO [w3schools].[dbo].[Orders] AS T USING [w3schools_copy].[dbo].[Orders] AS S ON T.[OrderID] = S.[OrderID] WHEN MATCHED AND ISNULL(T.[CustID], '''') != ISNULL(S.[CustID], '''') OR ISNULL(T.[EmpID], '''') != ISNULL(S.[EmpID], '''') OR ISNULL(T.[OrderDate], '''') != ISNULL(S.[OrderDate], '''') OR ISNULL(T.[ShipID], '''') != ISNULL(S.[ShipID], '''') THEN UPDATE SET T.[CustID] = S.[CustID], T.[EmpID] = S.[EmpID], T.[OrderDate] = S.[OrderDate], T.[ShipID] = S.[ShipID] ;';
EXECUTE [w3schools].sys.sp_executesql @command = N'MERGE INTO [w3schools].[dbo].[Products] AS T USING [w3schools_copy].[dbo].[Products] AS S ON T.[ProductID] = S.[ProductID] WHEN MATCHED AND ISNULL(T.[ProductName], '''') != ISNULL(S.[ProductName], '''') OR ISNULL(T.[SuplID], '''') != ISNULL(S.[SuplID], '''') OR ISNULL(T.[CatID], '''') != ISNULL(S.[CatID], '''') OR ISNULL(T.[Unit], '''') != ISNULL(S.[Unit], '''') OR ISNULL(T.[Price], 0) != ISNULL(S.[Price], 0) THEN UPDATE SET T.[ProductName] = S.[ProductName], T.[SuplID] = S.[SuplID], T.[CatID] = S.[CatID], T.[Unit] = S.[Unit], T.[Price] = S.[Price] ;';
EXECUTE [w3schools].sys.sp_executesql @command = N'MERGE INTO [w3schools].[dbo].[OrderDetails] AS T USING [w3schools_copy].[dbo].[OrderDetails] AS S ON T.[OrderDetailID] = S.[OrderDetailID] WHEN MATCHED AND ISNULL(T.[OrdID], '''') != ISNULL(S.[OrdID], '''') OR ISNULL(T.[ProdID], '''') != ISNULL(S.[ProdID], '''') OR ISNULL(T.[Quantity], '''') != ISNULL(S.[Quantity], '''') THEN UPDATE SET T.[OrdID] = S.[OrdID], T.[ProdID] = S.[ProdID], T.[Quantity] = S.[Quantity] ;';
